version: 2.1

jobs:     
  first-mvn-job-to-execute-tests:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command: |
            echo technotrainer tests to be executed.
            mvn clean test
      - store_test_results:
          path: /home/circleci/project/target/
      - store_artifacts:
          path: /home/circleci/project/target/site/jacoco
          destination: testcaseDetails

workflows:
  first-workflow-maven:
    jobs:
      - first-mvn-job-to-execute-tests      
  